load('../../common.Tiltfile', 'kustomize_resource')

kustomize_resource(
    workload='kafka',
    kustomization_path='./envs/local/',
    namespace='local',
    resource_deps=['strimzi'],
    labels=["infra"]
)