apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default:default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: default
subjects:
- kind: ServiceAccount
  name: default
  namespace: argo