version_settings(constraint='>=0.22.2')

load('ext://git_resource', 'git_checkout')

# checkout source code
project_name = 'nerdd-frontend'
repository_url = 'https://github.com/molinfo-vienna/nerdd-frontend.git'
project_dir = '../../repos/{}'.format(project_name)
if not os.path.exists(project_dir):
    git_checkout(
        repository_url, 
        checkout_dir=project_dir
    )

# build docker image
docker_build(
    'nerdd-frontend',
    context='../../repos/nerdd-frontend',
    dockerfile='Dockerfile.dev',
    live_update=[
        sync(project_dir, '/app')
    ],
)

# nerdd
k8s_yaml('deployment.yml')

k8s_resource(
    'nerdd-frontend',
    port_forwards=3000,
    labels=['frontend']
)