load('ext://git_resource', 'git_checkout')
load('../../common.Tiltfile', 'kustomize_resource')

# checkout source code
project_name = 'nerdd-frontend'
repository_url = 'https://github.com/molinfo-vienna/{}'.format(project_name)
project_dir = '../../repos/{}'.format(project_name)
if not os.path.exists(project_dir):
    git_checkout(
        repository_url, 
        checkout_dir=project_dir
    )

# build docker image
docker_build(
    'nerdd-frontend',
    context=project_dir,
    dockerfile='{}/Dockerfile.dev'.format(project_dir),
    live_update=[
        sync(project_dir, '/app')
    ],
)

# deploy to kubernetes
kustomize_resource(
    workload='nerdd-frontend',
    kustomization_path='./envs/local/',
    namespace='local',
    resource_deps=['nerdd-backend', 'traefik'],
    labels=['frontend']
)