load('ext://git_resource', 'git_checkout')
load('ext://namespace', 'namespace_inject')

# deploy yaml files
k8s_yaml(namespace_inject(kustomize('./envs/local/'), 'local'))

k8s_resource(
    new_name='storage', 
    objects=['pvc-media:persistentvolumeclaim'], 
    resource_deps=['namespace'],
    labels=['infra']
)