apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: system
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  partitions: 1
  replicas: 1
  config:
    cleanup.policy: compact