apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nerdd-code-apps
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://github.com/wschuell/nerdd.git
    targetRevision: HEAD
    path: appsets/3-code
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated: 
      prune: true 
      selfHeal: true