version_settings(constraint='>=0.31.2')

load('ext://git_resource', 'git_checkout')

# checkout source code
project_name = 'nerdd-link'
repository_url = 'https://github.com/molinfo-vienna/nerdd-link.git'
project_dir = '../../repos/{}'.format(project_name)
if not os.path.exists(project_dir):
    git_checkout(
        repository_url, 
        checkout_dir=project_dir
    )

# build the docker image
docker_build(
    'nerdd-process-jobs',
    context='../../repos/',
    dockerfile="Dockerfile",
    live_update=[
        sync(project_dir, '/app'),
        run('touch /app/CHANGES')
    ]
)

k8s_yaml('deployment.yml')

k8s_resource(
    'nerdd-process-jobs',
    resource_deps=['kafka', 'keda-operator', 'storage'],
    labels=["communication"],
)