version_settings(constraint='>=0.31.2')

allow_k8s_contexts('default')

# build the docker image
docker_build(
    'nerdd-init-system',
    context='.',
    dockerfile="Dockerfile",
)

k8s_yaml('job.yml')

k8s_resource(
    'nerdd-init-system',
    resource_deps=['kafka', 'keda-operator', 'storage'],
    labels=["communication"],
)