load('../../common.Tiltfile', 'kustomize_resource')

# deploy to kubernetes
kustomize_resource(
    workload='nerdd-init-system',
    kustomization_path='./envs/local/',
    namespace='local',
    resource_deps=['kafka', 'keda-operator', 'storage'],
    labels=['infra']
)