apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: strimzi-cluster-operator-leader-election
subjects:
  - kind: ServiceAccount
    name: strimzi-cluster-operator
    namespace: dev-kafka