version_settings(constraint='>=0.31.2')

allow_k8s_contexts('default')

docker_build(
    'cypstrate',
    context='../../cypstrate',
    dockerfile="Dockerfile",
    live_update=[
        sync('../../cypstrate', '/app'),
    ]
)

k8s_yaml('deployment.yml')
k8s_yaml('scaler.yml')

k8s_resource(
    'cypstrate',
    objects=['cypstrate-scaler'],
    resource_deps=['kafka', 'keda-operator'],
    labels=["nerdd-services"],
)