apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-appset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/molinfo-vienna/nerdd.git
      revision: HEAD
      directories:
      - path: apps/*/envs/infra
  template:
    metadata:
      name: '{{index .path.segments 1}}'
    spec:
      # The project the application belongs to.
      project: default
      # Source of the application manifests
      source:
        repoURL: https://github.com/molinfo-vienna/nerdd.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      
      # Destination cluster and namespace to deploy the application
      destination:
        server: https://kubernetes.default.svc
        # the namespaces of infra apps don't need to indicate the environment
        namespace: '{{index .path.segments 1}}'

      # Sync policy
      syncPolicy:
        syncOptions:
          - ServerSideApply=true
          - CreateNamespace=true  
        automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
          prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
          selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
      